version: '3'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - postgres

  dev:
    build: .
    entrypoint: yarn dev
    ports:
      - 80:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    links:
      - postgres

  app:
    build: .
    entrypoint: yarn start
    ports:
      - 80:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    links:
      - postgres

  test:
    build: .
    entrypoint: yarn test
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    links:
      - postgres

volumes:
  postgres-volume:
    driver: local